### ISSUE TITLE
Unexpected behavior: node_modules Ignored when combined with other patterns

### ISSUE THREAD

**Issue by j0nl1** [SuperchupuDev/tinyglobby#58] opened 2024-10-07 15:19 UTC
I'm not sure if this is the expected behavior, but it seems quite different from how fast-glob works. Essentially, when adding the node_modules folder and another pattern, the node_modules directory is ignored completely.

You can find a simple example reproducing this issue here:
https://stackblitz.com/edit/tinyglobby-behavior?file=glob.ts&view=editor

Is this the intended behavior? Any clarification would be appreciated!

Thanks in advance.

**Comment by SuperchupuDev** [comment] 2024-10-07 15:42
the `node_modules` folder generated by `pnpm` contains symlinks to packages from `node_modules/.pnpm`. sadly symlinks resolution had to be temporarily reverted due to a critical upstream bug, it will be reenabled once it gets fixed. you can track the following issues meanwhile:

- #54
- thecodrr/fdir#125

in theory, it should work once symlinks resolution is added back. meanwhile, i'm closing this as a duplicate of #10

by the way, unrelated to symlinks: you should set the `expandDirectories` `tinyglobby` option to `false` if you want to match `fast-glob`'s behavior as much as possible

**Closed by SuperchupuDev** 2024-10-07 15:42 UTC

**Comment by SuperchupuDev** [comment] 2024-10-25 07:39
fixed in 0.2.10. can you confirm the issue is solved?
