### ISSUE TITLE
Support for globStream

### ISSUE THREAD

**Issue by etnoy** [SuperchupuDev/tinyglobby#59] opened 2024-10-07 21:56 UTC
I'm looking to migrate from fast-glob, but I don't see a way to stream results like fast-glob does with globStream.

For very large directories with millions of files, node tends to crash due to running out of memory. We use globStream to paginate the result and manage the files in batches, but this appears not to be possible in tinyglobby yet.

**Comment by benmccann** [comment] 2024-10-07 21:59
I requested this in https://github.com/SuperchupuDev/tinyglobby/issues/24 earlier on, but hard to find as I didn't name it well. I just renamed it

**Comment by SuperchupuDev** [comment] 2024-10-07 22:01
this first needs streams support on thecodrr/fdir, duplicate of #24 though

**Closed** 2024-10-07 22:01 UTC
